steps:
  # Pull the previous image to use as cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull us-central1-docker.pkg.dev/tonal-land-477206-h3/stockaibot/stockaibot:latest || exit 0']

  # Build the container image using cache
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/tonal-land-477206-h3/stockaibot/stockaibot',
      '--cache-from', 'us-central1-docker.pkg.dev/tonal-land-477206-h3/stockaibot/stockaibot:latest',
      '.'
    ]
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/tonal-land-477206-h3/stockaibot/stockaibot']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'stockaibot'
      - '--image'
      - 'us-central1-docker.pkg.dev/tonal-land-477206-h3/stockaibot/stockaibot'
      - '--region'
      - 'us-central1'
      - '--service-account'
      - 'stock-ai@tonal-land-477206-h3.iam.gserviceaccount.com'


options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'us-central1-docker.pkg.dev/tonal-land-477206-h3/stockaibot/stockaibot'
